sudo: required
services:
  - docker

before_install:
  - docker build -t vijaybhdevops/travisimage -f Dockerfile.dev .

scripts:
  - docker run -it -e CI=true vijaybhdevops/travisimage npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "New-App"
  env: "NewApp-env"
  bucket_name: "elasticbeanstalk-ap-south-1-274723100691"
  bucket_path: "New-App"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
